# This is a basic workflow to help you get started with Actions

name: Count solved puzzles

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  count_solved:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Roughly estimate amount of solved puzzles
        run: |
          printf "Total puzzles solved: " 
          find ${GITHUB_WORKSPACE}/src -type d -maxdepth 2 -mindepth 2 | wc -l
